/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;


import Panels.*;
import myproject.Employee;
import java.*;
import java.io.Serializable;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author 3bqrano
 */
public class UpdateandDeleteEmployee extends javax.swing.JPanel implements Serializable {

    /**
     * Creates new form UpdateandDeleteEmployee
     */
    public UpdateandDeleteEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButtonsearch = new javax.swing.JButton();
        jTextFieldSearchKey = new javax.swing.JTextField();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNameEmployee = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jTextFieldPhoneNumber = new javax.swing.JTextField();
        jTextFieldQualification = new javax.swing.JTextField();
        jTextFieldDateofjoin = new javax.swing.JTextField();
        jTextFieldDateofBirthdate = new javax.swing.JTextField();
        jTextFieldUserName = new javax.swing.JTextField();
        jTextFieldPassword = new javax.swing.JTextField();
        jComboBoxGender = new javax.swing.JComboBox<>();
        jLabelSucessorfail = new javax.swing.JLabel();

        jButtonsearch.setText("Search");
        jButtonsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsearchActionPerformed(evt);
            }
        });

        jTextFieldSearchKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchKeyActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        jTextFieldNameEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameEmployeeActionPerformed(evt);
            }
        });

        jLabel2.setText("Gender");

        jLabel3.setText("Adderrs");

        jLabel4.setText("PhoneNumber");

        jLabel5.setText("Qualification");

        jLabel6.setText("DateOfJoin");

        jLabel7.setText("DateOfBirth");

        jLabel8.setText("UserName");

        jLabel9.setText("Password");

        jTextFieldAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddressActionPerformed(evt);
            }
        });

        jTextFieldDateofBirthdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDateofBirthdateActionPerformed(evt);
            }
        });

        jTextFieldUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserNameActionPerformed(evt);
            }
        });

        jTextFieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPasswordActionPerformed(evt);
            }
        });

        jComboBoxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));

        jLabelSucessorfail.setText("Write Emloyee Name to get all Info ...      before update or delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelSucessorfail))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNameEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextFieldSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jButtonsearch))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldAddress)
                            .addComponent(jTextFieldPhoneNumber)
                            .addComponent(jTextFieldQualification)
                            .addComponent(jTextFieldDateofjoin)
                            .addComponent(jTextFieldDateofBirthdate)
                            .addComponent(jTextFieldUserName)
                            .addComponent(jTextFieldPassword)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jButtonUpdate)
                        .addGap(89, 89, 89)
                        .addComponent(jButtonDelete)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonsearch))
                .addGap(18, 18, 18)
                .addComponent(jLabelSucessorfail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldNameEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextFieldQualification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldDateofjoin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldDateofBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonUpdate))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        if(!jTextFieldSearchKey.getText().equals("")){
            Employee x = new Employee();
            if(x.DeleteEmployee(jTextFieldSearchKey.getText())){
               jLabelSucessorfail.setText("Deleted Successfully ... !");
               resetPanelData();  
            } else {
                jLabelSucessorfail.setText("Failed to delete ... !");
            }
        }else {
            jLabelSucessorfail.setText("Missing required Fields ... !  Please, Search By Name before submitting ...!");
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jTextFieldNameEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameEmployeeActionPerformed

    private void jTextFieldAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddressActionPerformed

    private void jTextFieldDateofBirthdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDateofBirthdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDateofBirthdateActionPerformed

    private void jTextFieldUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUserNameActionPerformed

    private void jTextFieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPasswordActionPerformed

    private void jButtonsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsearchActionPerformed
        // TODO add your handling code here:
        if(!jTextFieldSearchKey.getText().equals("")) {
            Employee x = new Employee();
            Employee returned = x.SearchEmployee(jTextFieldSearchKey.getText());
            if (!returned.getName().isEmpty()) {
                setPanelData(returned);
            }
           
           else {
                jLabelSucessorfail.setText("Not Found ...!");
            }
        }
        else {
            jLabelSucessorfail.setText("Missing required Fields ... !  Please, Search By Name before submit ...!");
        } 
            
        
        
    }//GEN-LAST:event_jButtonsearchActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        if(!jTextFieldNameEmployee.getText().equals("") && !jTextFieldAddress.getText().equals("") && !jTextFieldPhoneNumber.getText().equals("") && !jTextFieldQualification.getText().equals("") && !jTextFieldDateofjoin.getText().equals("") && !jTextFieldDateofBirthdate.getText().equals("") && !jTextFieldUserName.getText().equals("")&& !jTextFieldPassword.getText().equals("") ){
            Employee x = new Employee();
            x.setName(jTextFieldNameEmployee.getText());
            x.setAddress(jTextFieldAddress.getText());
            Date d;
            try {
                
                d=new SimpleDateFormat("dd/MMM/yyyy").parse(jTextFieldDateofBirthdate.getText());
                x.setDateOfBirth(d);
            } catch (ParseException ex) {
                Logger.getLogger(UpdateandDeleteEmployee.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                
                d=new SimpleDateFormat("dd/MMM/yyyy").parse(jTextFieldDateofjoin.getText());
                x.setDateOfJoin(d);
            } catch (ParseException ex) {
                Logger.getLogger(UpdateandDeleteEmployee.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setPhoneNumber(jTextFieldPhoneNumber.getText());
            x.setQualification(jTextFieldQualification.getText());
            x.setUserName(jTextFieldUserName.getText());
            if(!jTextFieldPassword.getText().equals("")){
                x.setPassword(jTextFieldPassword.getText());
            }
            if(jComboBoxGender.getSelectedItem().equals("Female")){
                x.setGender("Female");
            }
            else if(jComboBoxGender.getSelectedItem().equals("Male")){
                x.setGender("Male");
            }
            if (x.UpdateEmployee()) {
               jLabelSucessorfail.setText("Updated Successfully ... !");
               resetPanelData();            
            } else{
                jLabelSucessorfail.setText("Failed to Update ... !");
            } 
    }                                                                                          

    private void jTextFieldSearchKeyActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                                                                      
        else {
             jLabelSucessorfail.setText("Missing required Fields ... !  Please, Search By Name before submit ...!");
            
        }
    }
    protected void resetPanelData() {
        jTextFieldNameEmployee.setText("");
        jTextFieldAddress.setText("");
        jTextFieldDateofjoin.setText("");
        jTextFieldDateofBirthdate.setText("");
        jTextFieldQualification.setText("");
        jTextFieldPhoneNumber.setText("");
        jTextFieldUserName.setText("");
        jTextFieldPassword.setText("");
        jComboBoxGender.setSelectedIndex(0);

    }
    protected void setPanelData(Employee x) {
        jTextFieldNameEmployee.setText("" + x.getName());
        if (x.getGender().equals("Female")){
          jComboBoxGender.setSelectedIndex(0);  
        } else if(x.getGender().equals("Male")){
           jComboBoxGender.setSelectedIndex(1);  
        }
        jTextFieldAddress.setText("" + x.getAddress());
        jTextFieldPhoneNumber.setText("" + x.getPhoneNumber());
        jTextFieldQualification.setText("" + x.getQualification());
        jTextFieldDateofjoin.setText("" + x.getDateOfJoin());
        jTextFieldDateofBirthdate.setText("" + x.getDateOfBirth());
        jTextFieldUserName.setText("" + x.getUserName());
        jTextFieldPassword.setText("" + x.getPassword());
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JButton jButtonsearch;
    private javax.swing.JComboBox<String> jComboBoxGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelSucessorfail;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldDateofBirthdate;
    private javax.swing.JTextField jTextFieldDateofjoin;
    private javax.swing.JTextField jTextFieldNameEmployee;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldPhoneNumber;
    private javax.swing.JTextField jTextFieldQualification;
    private javax.swing.JTextField jTextFieldSearchKey;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables
}
