/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import myproject.Driver;
import java.*;
import java.io.File;
import java.io.IOException;
import java.io.Serializable;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
/**
 *
 * @author SYSTEM
 */
public class Driver_Updatepanel extends javax.swing.JPanel implements Serializable {

    /**
     * Creates new form Driver_Updatepanel
     */
    public Driver_Updatepanel() {
        initComponents();
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jButtonSearch = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jTextFieldsearch = new javax.swing.JTextField();
        jTextFieldname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldAdress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldphone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldDate = new javax.swing.JTextField();
        jTextFieldsalary = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelanswer = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPhotoPath = new javax.swing.JTextField();
        jComboBoxGender = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabelPhoto = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        jLabel3.setText("Address");

        jLabel4.setText("Phone.NO");

        jLabel5.setText("Gender");

        jLabel6.setText("D.O.B");

        jTextFieldDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDateActionPerformed(evt);
            }
        });

        jLabel7.setText("Experience");

        jLabel8.setText("Salary");

        jLabelanswer.setText("Fill the Following");

        jLabel1.setText("Photo");

        jComboBoxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Expert", "beginner" }));

        jButton1.setText("upload");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabelanswer, javax.swing.GroupLayout.DEFAULT_SIZE, 977, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextFieldPhotoPath, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addComponent(jButton1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldname)
                            .addComponent(jTextFieldAdress)
                            .addComponent(jTextFieldsearch, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(jTextFieldphone, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldDate)
                            .addComponent(jTextFieldsalary)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButtonSearch))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabelPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldPhotoPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelanswer)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearch))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDateActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
        if (!jTextFieldsearch.getText().equals(""))
        {
        Driver x=new Driver ();
        Driver returned =x.SearchDriver(Integer.parseInt(jTextFieldsearch.getText()));
        if (!returned.getName().equals(""))
        {
        setpanelData(returned);
        }
        else  {
        jLabelanswer.setText("Not Found...!");
        
        }
       
        
        
        
        }
         else {
                jLabelanswer.setText("Missing information please complete it...!");
                }
          
        
    }//GEN-LAST:event_jButtonSearchActionPerformed

    
    
    
    
    
    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        if (!jTextFieldPhotoPath.getText().equals("")  &&!jTextFieldsalary.getText().equals("")&&!jTextFieldname.getText().equals("")&&!jTextFieldAdress.getText().equals("")&&!jTextFieldphone.getText().equals("")&&!jTextFieldDate.getText().equals(""))
        {
        
        Driver x=new Driver ();
        x.setID(Integer.parseInt(jTextFieldsearch.getText()));
        x.setSalary(Integer.parseInt(jTextFieldsalary.getText()));
        x.setAddress((jTextFieldAdress.getText()));
        x.setName(jTextFieldname.getText());
        
        if(jComboBoxGender.getSelectedIndex() == 0)
        {
            x.setGender("Male");
        }
        else 
            x.setGender("Female");
        
        
        if(jComboBox2.getSelectedIndex() == 0)
        {
            x.setExprience("Expert");
        }
        else 
            x.setExprience("Beginner");
        
        
       Date d;
        try{
               d=new SimpleDateFormat("dd/MM/yyyy").parse(jTextFieldDate.getText());
                x.SetDateOfBirth(d); 
            }
            catch(ParseException ex){
                Logger.getLogger(Driver_Addpanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
        x.setPhoneNumber(jTextFieldphone.getText());
        
        x.setPhoto(jTextFieldPhotoPath.getText());
        
        if (x.UpdateDriver())
        {
        jLabelanswer.setText("Updated successfully...!");
        resetpanelData();    
        }
        else 
        {
         jLabelanswer.setText("Failed to update...!");
        }            
        }
                else { jLabelanswer.setText("Missing information please complete it...!");}

        
        
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        
        if (!jTextFieldsearch.getText().equals(""))
        {Driver x=new Driver ();
        if (x.DeleteDriver(Integer.parseInt(jTextFieldsearch.getText())))
        {
            jLabelanswer.setText("Deleted Successfully...!");
          resetpanelData();
        }
        else 
        {
        jLabelanswer.setText("Failed to delete...!");
        
        }
        
      
        }
        else {
        
        jLabelanswer.setText("Missing information please complete it...!");
        
        }
        
        
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String filename = "image1.png";
        
        JFileChooser chooser = new JFileChooser(); 
          
        chooser.showOpenDialog(null);
          
        File f = chooser.getSelectedFile();
          if(f.isFile()) 
                 filename = f.getAbsolutePath();
            
              jTextFieldPhotoPath.setText(filename);
           
              try{
                ImageIcon icon = new ImageIcon(ImageIO.read(new File(filename)));
                
                jLabelPhoto.setIcon(icon);
            }
            catch(IOException e){
                System.out.println(e);
            }
        
          
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
     protected void setpanelData(Driver x)
{
jTextFieldname.setText(""+x.getName());
jTextFieldAdress.setText(""+x.getAddress());
jTextFieldphone.setText(""+x.getPhoneNumber());
jTextFieldDate.setText(""+x.getDateOfBirth());
jTextFieldsalary.setText(""+x.getSalary());
jTextFieldPhotoPath.setText(""+ x.getPhoto()) ;
jTextFieldPhotoPath.setText(""+x.getPhoto());
try{
                ImageIcon icon = new ImageIcon(ImageIO.read(new File(x.getPhoto())));
                jLabelPhoto.setIcon(icon);
            }
            catch(IOException e){
                System.out.println(e);
            }



if(x.getGender().equals("Male"))
{
    jComboBoxGender.setSelectedIndex(0);
}
else 
    jComboBoxGender.setSelectedIndex(1);

if(x.getExprience().equals("Expert"))
{
  jComboBox2.setSelectedIndex(0);
}
else 
   jComboBox2.setSelectedIndex(1);


}
     protected void resetpanelData()
     {
         
jTextFieldname.setText("");
jTextFieldAdress.setText("");
jTextFieldphone.setText("");
jTextFieldDate.setText("");
jTextFieldsalary.setText("");
jTextFieldPhotoPath.setText("");
     
jComboBox2.setSelectedIndex(0);
jComboBoxGender.setSelectedIndex(0);     

     }
     
     
    
    
    
    
    
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBoxGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelPhoto;
    private javax.swing.JLabel jLabelanswer;
    private javax.swing.JTextField jTextFieldAdress;
    private javax.swing.JTextField jTextFieldDate;
    private javax.swing.JTextField jTextFieldPhotoPath;
    private javax.swing.JTextField jTextFieldname;
    private javax.swing.JTextField jTextFieldphone;
    private javax.swing.JTextField jTextFieldsalary;
    private javax.swing.JTextField jTextFieldsearch;
    // End of variables declaration//GEN-END:variables

    
}

