/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import java.*;
import java.io.Serializable;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import myproject.*;


/**
 *
 * @author toshiba
 */
public class UpdateandDeleteEmployee extends javax.swing.JPanel {

    /**
     * Creates new form any
     */
    
    public UpdateandDeleteEmployee() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldPhoneNumber = new javax.swing.JTextField();
        jTextFieldNameEmployee = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDateofjoin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDateofBirthdate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldUserName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPassword = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxGender = new javax.swing.JComboBox<>();
        jButtonsearch = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabelSucessorfail = new javax.swing.JLabel();
        jTextFieldSearchKey = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButtonUpdate = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButtonDelete = new javax.swing.JButton();
        jTextFieldAddress = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxQualification = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(204, 204, 255));

        jTextFieldNameEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameEmployeeActionPerformed(evt);
            }
        });

        jLabel2.setText("Gender");

        jLabel3.setText("Adderrs");

        jTextFieldDateofBirthdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDateofBirthdateActionPerformed(evt);
            }
        });

        jLabel4.setText("PhoneNumber");

        jTextFieldUserName.setEditable(false);
        jTextFieldUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserNameActionPerformed(evt);
            }
        });

        jLabel5.setText("Qualification");

        jTextFieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPasswordActionPerformed(evt);
            }
        });

        jLabel6.setText("DateOfJoin");

        jComboBoxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));

        jButtonsearch.setText("Search");
        jButtonsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsearchActionPerformed(evt);
            }
        });

        jLabel7.setText("DateOfBirth");

        jLabelSucessorfail.setText("Write Emloyee Name to get all Info ...      before update or delete");

        jTextFieldSearchKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchKeyActionPerformed(evt);
            }
        });

        jLabel8.setText("UserName");

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jLabel9.setText("Password");

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jTextFieldAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddressActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        jComboBoxQualification.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Graduate", "Expert", "Student" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSucessorfail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextFieldSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jButtonsearch)))
                .addGap(138, 138, 138))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldDateofBirthdate, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldDateofjoin, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPhoneNumber, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldUserName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxQualification, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButtonUpdate)
                        .addGap(97, 97, 97)
                        .addComponent(jButtonDelete))
                    .addComponent(jComboBoxGender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNameEmployee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addComponent(jTextFieldPassword))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonsearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSucessorfail)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNameEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxQualification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldDateofjoin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldDateofBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUpdate)
                    .addComponent(jButtonDelete))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNameEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameEmployeeActionPerformed

    private void jTextFieldDateofBirthdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDateofBirthdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDateofBirthdateActionPerformed

    private void jTextFieldUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUserNameActionPerformed

    private void jTextFieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPasswordActionPerformed

    private void jButtonsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsearchActionPerformed
        // TODO add your handling code here:
        if(!jTextFieldSearchKey.getText().equals("")) {
            Employee x = new Employee();
            Employee returned = x.SearchEmployee(jTextFieldSearchKey.getText());
            if (!returned.getUserName().isEmpty()) {
                setPanelData(returned);
            }

            else {
                jLabelSucessorfail.setText("Not Found ...!");
            }
        }
        else {
            jLabelSucessorfail.setText("Missing required Fields ... !  Please, Search By Name before submit ...!");
        }

    }//GEN-LAST:event_jButtonsearchActionPerformed

    private void jTextFieldSearchKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchKeyActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        if(!jTextFieldNameEmployee.getText().equals("") && !jTextFieldAddress.getText().equals("") && !jTextFieldPhoneNumber.getText().equals("") && !jTextFieldDateofjoin.getText().equals("") && !jTextFieldDateofBirthdate.getText().equals("") && !jTextFieldUserName.getText().equals("")&& !jTextFieldPassword.getText().equals("") ){
            Employee x=new Employee();
            x.setName(jTextFieldNameEmployee.getText());
            x.setAddress(jTextFieldAddress.getText());
            x.setPhoneNumber(jTextFieldPhoneNumber.getText());
            x.setDateOfJoin(jTextFieldDateofjoin.getText());
            x.setDateOfBirth(jTextFieldDateofBirthdate.getText());
            if(jComboBoxQualification.getSelectedIndex()==0)
            x.setQualification("Graduate");
            else if(jComboBoxQualification.getSelectedIndex()==1)
                x.setQualification("Expert");
            else
                x.setQualification("Student");
            
            x.setUserName(jTextFieldUserName.getText());
            x.setPassword(jTextFieldPassword.getText());
            
            
            if(jComboBoxGender.getSelectedIndex() == 0){
                x.setGender("Female");
            }
            else
                x.setGender("Male");
            
            if (x.UpdateEmployee()) {
                jLabelSucessorfail.setText("Updated Successfully ... !");
                resetPanelData();
            } else{
                jLabelSucessorfail.setText("Failed to Update ... !");
            }
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        if(!jTextFieldSearchKey.getText().equals("")){
            Employee x = new Employee();
            if(x.DeleteEmployee(jTextFieldSearchKey.getText())){
                jLabelSucessorfail.setText("Deleted Successfully ... !");
                resetPanelData();
            } else {
                jLabelSucessorfail.setText("Failed to delete ... !");
            }
        }else {
            jLabelSucessorfail.setText("Missing required Fields ... !  Please, Search By Name before submitting ...!");
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jTextFieldAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddressActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JButton jButtonsearch;
    private javax.swing.JComboBox<String> jComboBoxGender;
    private javax.swing.JComboBox<String> jComboBoxQualification;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelSucessorfail;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldDateofBirthdate;
    private javax.swing.JTextField jTextFieldDateofjoin;
    private javax.swing.JTextField jTextFieldNameEmployee;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldPhoneNumber;
    private javax.swing.JTextField jTextFieldSearchKey;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables

    private void resetPanelData() {
       jTextFieldAddress.setText("");
       jTextFieldDateofBirthdate.setText("");
       jTextFieldDateofjoin.setText("");
       jTextFieldNameEmployee.setText("");
       jTextFieldPassword.setText("");
       jTextFieldPhoneNumber.setText(""); 
       jComboBoxQualification.setSelectedIndex(-1);
       jTextFieldSearchKey.setText("");
       jTextFieldUserName.setText("");
    }

    private void setPanelData(Employee returned) {
        jTextFieldAddress.setText(""+returned.getAddress());
       jTextFieldDateofBirthdate.setText(""+returned.getDateOfBirth());
       jTextFieldDateofjoin.setText(""+returned.getDateOfJoin());
       jTextFieldNameEmployee.setText(""+returned.getName());
       jTextFieldPassword.setText(""+returned.getPassword());
       jTextFieldPhoneNumber.setText(""+returned.getPhoneNumber());
       jTextFieldUserName.setText(""+returned.getUserName());
       if(returned.getQualification().equals("Graduate"))
           jComboBoxQualification.setSelectedIndex(0);
       else if(returned.getQualification().equals("Expert"))
           jComboBoxQualification.setSelectedIndex(1);
       else
           jComboBoxQualification.setSelectedIndex(2);
    
    if(returned.getGender().equals("Female"))
    {
        jComboBoxGender.setSelectedIndex(0);
    }
    else
        jComboBoxGender.setSelectedIndex(0);
    
    
    }
        
    }
